### ISSUE TITLE
1.2 See Scheduled Medications

### ISSUE THREAD

**Issue by briggsyj** [QUTCaptstone2017/trackmymeds_android#1]
Description - I want to be able to see any scheduled medicines and set times to take the medicine.
Acceptance - Must be a page that shows all scheduled medicines for the day and have the ability to change these set times.

- [x] Frontend Complete

- [x] Backend Complete
expects:
**auth**[_mobile_token_]
**data**[_med_product_id_, _start_date_ (YYYY-MM-DD), _time_ (HH:MM), _interval_, _dosage_, _items_remaining_, _nickname_]
returns
**auth**[_is_valid_, _mobile_token_, _error_code_]

**Comment by DecsterB** [comment]
Working but requires more to be done.

TODO:
Filter by morning or afternoon.
Tabs for Daily and All.
Storing the medication details locally.
Refreshing to match live server data.
